Add the actual OpenFold installation step in Installation.md
Not sure if this the way you want it but otherwise OpenFold would not be installed... And you'd get error like this:

srun --time=1-00:00:00 -p gpu-el8 -G 1 --mem-per-gpu 32000 --qos=highest scripts/run_unit_tests.sh
srun: job 4368915 queued and waiting for resources
srun: job 4368915 has been allocated resources
/g/kosinski/kosinski/software/envs/openfold_env/lib/python3.9/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
[2024-05-19 13:02:40,227] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
E.................EEEEEEEEEEEE...EEEEEE
======================================================================
ERROR: tests.test_data_pipeline (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_data_pipeline
Traceback (most recent call last):
  File "/g/kosinski/kosinski/software/envs/openfold_env/lib/python3.9/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/g/kosinski/kosinski/software/envs/openfold_env/lib/python3.9/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/g/kosinski/kosinski/software/openfold/tests/test_data_pipeline.py", line 23, in <module>
    import tests.compare_utils as compare_utils
  File "/g/kosinski/kosinski/software/openfold/tests/compare_utils.py", line 12, in <module>
    from openfold.model.model import AlphaFold
  File "/g/kosinski/kosinski/software/openfold/openfold/model/model.py", line 29, in <module>
    from openfold.model.embedders import (
  File "/g/kosinski/kosinski/software/openfold/openfold/model/embedders.py", line 29, in <module>
    from openfold.model.primitives import Linear, LayerNorm
  File "/g/kosinski/kosinski/software/openfold/openfold/model/primitives.py", line 38, in <module>
    from openfold.utils.kernel.attention_core import attention_core
  File "/g/kosinski/kosinski/software/openfold/openfold/utils/kernel/attention_core.py", line 20, in <module>
    attn_core_inplace_cuda = importlib.import_module("attn_core_inplace_cuda")
  File "/g/kosinski/kosinski/software/envs/openfold_env/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'attn_core_inplace_cuda'